import 'package:flutter/material.dart';
import 'package:from_css_color/from_css_color.dart';

// Note: Constant Values
const defaultPadding = EdgeInsets.fromLTRB(24, 24, 24, 24);
const paddingLeftRight = EdgeInsets.only(left: 24, right: 24);
const paddingSide = EdgeInsets.only(left: 20, right: 20);
const double padding3XS = 1;
const double padding2XS = 2;
const double paddingXS = 4;
const double paddingS = 6;
const double paddingM = 8;
const double paddingLa = 10;
const double paddingL2 = 12;
const double paddingL = 16;
const double paddingXL = 18;
const double padding2XL = 24;
const double paddingXL2 = 25;
const double padding3XL = 28;
const double padding4XL = 32;
const double padding5XL = 36;
const double padding6XL = 64;
const double padding7XL = 72;
const double padding8XL = 92;
const double padding9XL = 100;
const double padding10XL = 140;

const double rounded = 16;
const double roundedCardIcon = 30;
const double roundedCard = 32;
const double spaceHeight = 12;
const double spaceHeightXL = 24;
const double spaceWidth = 12;

// Note: Colors
Color colorTextBold = const Color(0xFF212121);
Color colorText = const Color(0xff424242);
Color blueMain = fromCssColor('#0E529D');
Color colorForm = const Color(0xFFf3f3f3);
Color colorCard = const Color(0xFFE7E7E7);
Color primaryColor = const Color.fromARGB(255, 7, 114, 177);
Color blackColor = const Color(0xFF101010);
Color whiteColor = const Color(0xffFFFFFF);
Color redColor = const Color(0xffFD4F56);
Color greyColor = const Color(0xffB3B5C4);
Color transparentColor = Colors.transparent;
Color inputFieldColor = const Color(0xffF1F0F5);
Color greenColor = Colors.green;
Color brownColor = const Color.fromARGB(255, 139, 114, 3);
Color tealColor = Colors.teal;
const accentColor = Color(0xFF53B966);
const headlineColor = Color(0xFF181818);
const textColor = Color(0xFF7d7d7d);
const dangerColor = Color(0xFFDA2525);
const buttonColor = Color(0xff009688);
Color colorBorder = fromCssColor("#C2C2C2");
Color fontGrey = fromCssColor('#858585');
Color baseColor = Colors.grey[300]!;
Color highlightColor = Colors.grey[100]!;
Color borderColor = const Color(0XFFCCCCCC);
